//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryGuessWho.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public long ACCOUNTID { get; set; }
        public long USERID { get; set; }
        public string EMAIL { get; set; }
        public byte[] PASSWORD { get; set; }
        public bool ISEMAILVERIFIED { get; set; }
        public Nullable<System.DateTime> LASTLOGINUTC { get; set; }
        public int FAILEDLOGINS { get; set; }
        public Nullable<System.DateTime> LOCKEDUNTILUTC { get; set; }
        public System.DateTime CREATEDATUTC { get; set; }
        public System.DateTime UPDATEDATUTC { get; set; }
    
        public virtual USER_PROFILE USER_PROFILE { get; set; }
    }
}
