//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryGuessWho.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNT()
        {
            this.EMAIL_VERIFICATION = new HashSet<EMAIL_VERIFICATION>();
        }
    
        public long ACCOUNTID { get; set; }
        public long USERID { get; set; }
        public string EMAIL { get; set; }
        public byte[] PASSWORD { get; set; }
        public bool ISEMAILVERIFIED { get; set; }
        public Nullable<System.DateTime> LASTLOGINUTC { get; set; }
        public int FAILEDLOGINS { get; set; }
        public Nullable<System.DateTime> LOCKEDUNTILUTC { get; set; }
        public System.DateTime CREATEDATUTC { get; set; }
        public System.DateTime UPDATEDATUTC { get; set; }
        public bool ISDELETED { get; set; }
        public Nullable<System.DateTime> DELETEDATUTC { get; set; }
    
        public virtual USER_PROFILE USER_PROFILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAIL_VERIFICATION> EMAIL_VERIFICATION { get; set; }
    }
}
