//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryGuessWho.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHARACTER
    {
        public long CHARACTERID { get; set; }
        public long CHARACTERSETID { get; set; }
        public string DISPLAYNAME { get; set; }
        public string IMAGEURL { get; set; }
        public bool ISACTIVE { get; set; }
    
        public virtual CHARACTER_SET CHARACTER_SET { get; set; }
    }
}
