//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryGuessWho.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_VERIFICATION
    {
        public System.Guid TOKENID { get; set; }
        public long ACCOUNTID { get; set; }
        public byte[] CODEHASH { get; set; }
        public System.DateTime EXPIRESUTC { get; set; }
        public Nullable<System.DateTime> CONSUMEDUTC { get; set; }
        public System.DateTime CREATEDATUTC { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
    }
}
