//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryGuessWho.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRIENDSHIP
    {
        public long FRIENDSHIPID { get; set; }
        public long USER1ID { get; set; }
        public long USER2ID { get; set; }
        public System.DateTime CREATEDATUTC { get; set; }
        public long USERIDLOW { get; set; }
        public long USERIDHIGH { get; set; }
    
        public virtual USER_PROFILE USER_PROFILE { get; set; }
        public virtual USER_PROFILE USER_PROFILE1 { get; set; }
        public long USERID1 { get; internal set; }
        public long USERID2 { get; internal set; }
    }
}
