//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryGuessWho.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRIEND_REQUEST
    {
        public long FRIENDREQUESTID { get; set; }
        public long REQUESTERUSERID { get; set; }
        public long ADDRESSEEUSERID { get; set; }
        public byte STATUSID { get; set; }
        public System.DateTime CREATEDATUTC { get; set; }
        public Nullable<System.DateTime> RESPONDEDATUTC { get; set; }
    
        public virtual USER_PROFILE USER_PROFILE { get; set; }
        public virtual USER_PROFILE USER_PROFILE1 { get; set; }
        public virtual FRIENDREQUESTSTATUS FRIENDREQUESTSTATUS { get; set; }
    }
}
