//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhoDataAccess.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GuessWhoDBEntities : DbContext
    {
        public GuessWhoDBEntities()
            : base("name=GuessWhoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNT { get; set; }
        public virtual DbSet<AVATAR> AVATAR { get; set; }
        public virtual DbSet<CHARACTER> CHARACTER { get; set; }
        public virtual DbSet<EMAIL_VERIFICATION> EMAIL_VERIFICATION { get; set; }
        public virtual DbSet<FRIEND_REQUEST> FRIEND_REQUEST { get; set; }
        public virtual DbSet<FRIENDREQUESTSTATUS> FRIENDREQUESTSTATUS { get; set; }
        public virtual DbSet<FRIENDSHIP> FRIENDSHIP { get; set; }
        public virtual DbSet<GUEST_SESSION> GUEST_SESSION { get; set; }
        public virtual DbSet<MATCH> MATCH { get; set; }
        public virtual DbSet<MATCH_CHAT_MESSAGE> MATCH_CHAT_MESSAGE { get; set; }
        public virtual DbSet<MATCH_DECK_CARD> MATCH_DECK_CARD { get; set; }
        public virtual DbSet<MATCH_INVITATION> MATCH_INVITATION { get; set; }
        public virtual DbSet<MATCH_MODE> MATCH_MODE { get; set; }
        public virtual DbSet<MATCH_PLAYER> MATCH_PLAYER { get; set; }
        public virtual DbSet<MATCH_TURN_ORDER> MATCH_TURN_ORDER { get; set; }
        public virtual DbSet<MATCH_TURN_STATE> MATCH_TURN_STATE { get; set; }
        public virtual DbSet<MATCHSTATUS> MATCHSTATUS { get; set; }
        public virtual DbSet<MATCHVISIBILITY> MATCHVISIBILITY { get; set; }
        public virtual DbSet<MODERATION_ACTION> MODERATION_ACTION { get; set; }
        public virtual DbSet<MODERATION_REPORT> MODERATION_REPORT { get; set; }
        public virtual DbSet<MODERATIONACTIONTYPE> MODERATIONACTIONTYPE { get; set; }
        public virtual DbSet<MODERATIONSCOPE> MODERATIONSCOPE { get; set; }
        public virtual DbSet<TOURNAMENT_4P> TOURNAMENT_4P { get; set; }
        public virtual DbSet<TOURNAMENT_4P_MATCH> TOURNAMENT_4P_MATCH { get; set; }
        public virtual DbSet<TOURNAMENT_4P_PLAYER> TOURNAMENT_4P_PLAYER { get; set; }
        public virtual DbSet<TOURNAMENTSTATUS> TOURNAMENTSTATUS { get; set; }
        public virtual DbSet<USER_PROFILE> USER_PROFILE { get; set; }
    
        public virtual int SP_ACCEPTFRIENDREQUEST(Nullable<long> fRIENDREQUESTID)
        {
            var fRIENDREQUESTIDParameter = fRIENDREQUESTID.HasValue ?
                new ObjectParameter("FRIENDREQUESTID", fRIENDREQUESTID) :
                new ObjectParameter("FRIENDREQUESTID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACCEPTFRIENDREQUEST", fRIENDREQUESTIDParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int SP_CREATEFRIENDREQUEST(Nullable<long> rEQUESTERUSERID, Nullable<long> aDDRESSEEUSERID)
        {
            var rEQUESTERUSERIDParameter = rEQUESTERUSERID.HasValue ?
                new ObjectParameter("REQUESTERUSERID", rEQUESTERUSERID) :
                new ObjectParameter("REQUESTERUSERID", typeof(long));
    
            var aDDRESSEEUSERIDParameter = aDDRESSEEUSERID.HasValue ?
                new ObjectParameter("ADDRESSEEUSERID", aDDRESSEEUSERID) :
                new ObjectParameter("ADDRESSEEUSERID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATEFRIENDREQUEST", rEQUESTERUSERIDParameter, aDDRESSEEUSERIDParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int SP_ACCEPTFRIENDREQUEST1(Nullable<long> fRIENDREQUESTID)
        {
            var fRIENDREQUESTIDParameter = fRIENDREQUESTID.HasValue ?
                new ObjectParameter("FRIENDREQUESTID", fRIENDREQUESTID) :
                new ObjectParameter("FRIENDREQUESTID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACCEPTFRIENDREQUEST1", fRIENDREQUESTIDParameter);
        }
    
        public virtual int SP_CREATEFRIENDREQUEST1(Nullable<long> rEQUESTERUSERID, Nullable<long> aDDRESSEEUSERID)
        {
            var rEQUESTERUSERIDParameter = rEQUESTERUSERID.HasValue ?
                new ObjectParameter("REQUESTERUSERID", rEQUESTERUSERID) :
                new ObjectParameter("REQUESTERUSERID", typeof(long));
    
            var aDDRESSEEUSERIDParameter = aDDRESSEEUSERID.HasValue ?
                new ObjectParameter("ADDRESSEEUSERID", aDDRESSEEUSERID) :
                new ObjectParameter("ADDRESSEEUSERID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATEFRIENDREQUEST1", rEQUESTERUSERIDParameter, aDDRESSEEUSERIDParameter);
        }
    
        public virtual ObjectResult<EmailVerification_Resend_Result> EmailVerification_Resend(Nullable<long> accountId, byte[] codeHash, Nullable<System.DateTime> expiresUtc)
        {
            var accountIdParameter = accountId.HasValue ?
                new ObjectParameter("AccountId", accountId) :
                new ObjectParameter("AccountId", typeof(long));
    
            var codeHashParameter = codeHash != null ?
                new ObjectParameter("CodeHash", codeHash) :
                new ObjectParameter("CodeHash", typeof(byte[]));
    
            var expiresUtcParameter = expiresUtc.HasValue ?
                new ObjectParameter("ExpiresUtc", expiresUtc) :
                new ObjectParameter("ExpiresUtc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmailVerification_Resend_Result>("EmailVerification_Resend", accountIdParameter, codeHashParameter, expiresUtcParameter);
        }
    
        public virtual int usp_Match_HandleDisconnect(Nullable<long> userId, Nullable<System.DateTime> nowUtc, Nullable<byte> matchStatusLobby, Nullable<byte> matchStatusActive, Nullable<byte> matchStatusFinished, Nullable<byte> matchStatusCancelled)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var nowUtcParameter = nowUtc.HasValue ?
                new ObjectParameter("NowUtc", nowUtc) :
                new ObjectParameter("NowUtc", typeof(System.DateTime));
    
            var matchStatusLobbyParameter = matchStatusLobby.HasValue ?
                new ObjectParameter("MatchStatusLobby", matchStatusLobby) :
                new ObjectParameter("MatchStatusLobby", typeof(byte));
    
            var matchStatusActiveParameter = matchStatusActive.HasValue ?
                new ObjectParameter("MatchStatusActive", matchStatusActive) :
                new ObjectParameter("MatchStatusActive", typeof(byte));
    
            var matchStatusFinishedParameter = matchStatusFinished.HasValue ?
                new ObjectParameter("MatchStatusFinished", matchStatusFinished) :
                new ObjectParameter("MatchStatusFinished", typeof(byte));
    
            var matchStatusCancelledParameter = matchStatusCancelled.HasValue ?
                new ObjectParameter("MatchStatusCancelled", matchStatusCancelled) :
                new ObjectParameter("MatchStatusCancelled", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Match_HandleDisconnect", userIdParameter, nowUtcParameter, matchStatusLobbyParameter, matchStatusActiveParameter, matchStatusFinishedParameter, matchStatusCancelledParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_Match_StartAtomic(Nullable<long> matchId, Nullable<long> hostUserId, Nullable<System.DateTime> nowUtc, Nullable<int> expectedPlayers, Nullable<byte> hostSlotNumber, Nullable<byte> guestSlotNumber, Nullable<byte> matchStatusLobby, Nullable<byte> matchStatusActive)
        {
            var matchIdParameter = matchId.HasValue ?
                new ObjectParameter("MatchId", matchId) :
                new ObjectParameter("MatchId", typeof(long));
    
            var hostUserIdParameter = hostUserId.HasValue ?
                new ObjectParameter("HostUserId", hostUserId) :
                new ObjectParameter("HostUserId", typeof(long));
    
            var nowUtcParameter = nowUtc.HasValue ?
                new ObjectParameter("NowUtc", nowUtc) :
                new ObjectParameter("NowUtc", typeof(System.DateTime));
    
            var expectedPlayersParameter = expectedPlayers.HasValue ?
                new ObjectParameter("ExpectedPlayers", expectedPlayers) :
                new ObjectParameter("ExpectedPlayers", typeof(int));
    
            var hostSlotNumberParameter = hostSlotNumber.HasValue ?
                new ObjectParameter("HostSlotNumber", hostSlotNumber) :
                new ObjectParameter("HostSlotNumber", typeof(byte));
    
            var guestSlotNumberParameter = guestSlotNumber.HasValue ?
                new ObjectParameter("GuestSlotNumber", guestSlotNumber) :
                new ObjectParameter("GuestSlotNumber", typeof(byte));
    
            var matchStatusLobbyParameter = matchStatusLobby.HasValue ?
                new ObjectParameter("MatchStatusLobby", matchStatusLobby) :
                new ObjectParameter("MatchStatusLobby", typeof(byte));
    
            var matchStatusActiveParameter = matchStatusActive.HasValue ?
                new ObjectParameter("MatchStatusActive", matchStatusActive) :
                new ObjectParameter("MatchStatusActive", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_Match_StartAtomic", matchIdParameter, hostUserIdParameter, nowUtcParameter, expectedPlayersParameter, hostSlotNumberParameter, guestSlotNumberParameter, matchStatusLobbyParameter, matchStatusActiveParameter);
        }
    
        public virtual int uspMatchTurn_Initialize(Nullable<long> matchId, Nullable<System.DateTime> nowUtc, Nullable<System.DateTime> turnExpiresAtUtc)
        {
            var matchIdParameter = matchId.HasValue ?
                new ObjectParameter("MatchId", matchId) :
                new ObjectParameter("MatchId", typeof(long));
    
            var nowUtcParameter = nowUtc.HasValue ?
                new ObjectParameter("NowUtc", nowUtc) :
                new ObjectParameter("NowUtc", typeof(System.DateTime));
    
            var turnExpiresAtUtcParameter = turnExpiresAtUtc.HasValue ?
                new ObjectParameter("TurnExpiresAtUtc", turnExpiresAtUtc) :
                new ObjectParameter("TurnExpiresAtUtc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspMatchTurn_Initialize", matchIdParameter, nowUtcParameter, turnExpiresAtUtcParameter);
        }
    }
}
