//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhoDataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUEST_SESSION
    {
        public System.Guid GUESTTOKEN { get; set; }
        public long USERID { get; set; }
        public System.DateTime CREATEDATUTC { get; set; }
        public System.DateTime EXPIRESATUTC { get; set; }
    
        public virtual USER_PROFILE USER_PROFILE { get; set; }
    }
}
