//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryGuessWho.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATCH_PLAYER
    {
        public long MATCHID { get; set; }
        public long USERID { get; set; }
        public Nullable<byte> SLOTNUMBER { get; set; }
        public bool ISWINNER { get; set; }
        public System.DateTime JOINEDATUTC { get; set; }
        public Nullable<System.DateTime> LEFTATUTC { get; set; }
        public bool ISHOST { get; set; }
        public bool ISREADY { get; set; }
        public string SECRETCHARACTERID { get; set; }
    
        public virtual CHARACTER CHARACTER { get; set; }
        public virtual USER_PROFILE USER_PROFILE { get; set; }
        public virtual MATCH MATCH { get; set; }
        public virtual MATCH MATCH1 { get; set; }
    }
}
