//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryGuessWho.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATCH_TURN_ORDER
    {
        public long MATCHID { get; set; }
        public byte POSITION { get; set; }
        public long USERID { get; set; }
        public System.DateTime CREATEDATUTC { get; set; }
    
        public virtual MATCH MATCH { get; set; }
        public virtual USER_PROFILE USER_PROFILE { get; set; }
    }
}
