//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryGuessWho.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATCH_TURN_STATE
    {
        public long MATCHID { get; set; }
        public int TURNNUMBER { get; set; }
        public byte CURRENTPOSITION { get; set; }
        public long CURRENTUSERID { get; set; }
        public System.DateTime TURNSTARTEDATUTC { get; set; }
        public Nullable<System.DateTime> TURNEXPIRESATUTC { get; set; }
        public byte[] ROWVERSION { get; set; }
    
        public virtual MATCH MATCH { get; set; }
        public virtual USER_PROFILE USER_PROFILE { get; set; }
    }
}
