//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryGuessWho.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATCH_DECK_CARD
    {
        public long MATCHID { get; set; }
        public int POSITION { get; set; }
        public string CHARACTERID { get; set; }
    
        public virtual CHARACTER CHARACTER { get; set; }
        public virtual MATCH MATCH { get; set; }
    }
}
