//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryGuessWho.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATCH_INVITATION
    {
        public long MATCHINVITATIONID { get; set; }
        public long MATCHID { get; set; }
        public long INVITERUSERID { get; set; }
        public Nullable<long> TARGETUSERID { get; set; }
        public string TARGETEMAIL { get; set; }
        public System.Guid TOKEN { get; set; }
        public byte INVITATIONSTATUS { get; set; }
        public System.DateTime CREATEDATUTC { get; set; }
        public Nullable<System.DateTime> RESPONDEDATUTC { get; set; }
    
        public virtual USER_PROFILE USER_PROFILE { get; set; }
        public virtual USER_PROFILE USER_PROFILE1 { get; set; }
        public virtual MATCH MATCH { get; set; }
    }
}
