//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryGuessWho.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATCH_MODE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATCH_MODE()
        {
            this.MATCH = new HashSet<MATCH>();
        }
    
        public byte MODEID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int DEFAULT_DECK_SIZE { get; set; }
        public int DEFAULT_TURN_TIME_SEC { get; set; }
        public Nullable<int> DEFAULT_MATCH_DURATION_SEC { get; set; }
        public byte DEFAULT_MAX_PLAYERS { get; set; }
        public bool IS_ACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATCH> MATCH { get; set; }
    }
}
