//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhoDataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODERATION_REPORT
    {
        public long REPORTID { get; set; }
        public long MATCHID { get; set; }
        public long REPORTERUSERID { get; set; }
        public long TARGETUSERID { get; set; }
        public string REASON { get; set; }
        public System.DateTime CREATEDATUTC { get; set; }
    }
}
