//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryGuessWho.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODERATION_ACTION
    {
        public long MODERATIONID { get; set; }
        public long TARGETUSERID { get; set; }
        public Nullable<long> MODERATORUSERID { get; set; }
        public byte ACTIONTYPEID { get; set; }
        public string REASON { get; set; }
        public int DURATIONMINUTES { get; set; }
        public byte SCOPEID { get; set; }
        public Nullable<long> MATCHID { get; set; }
        public System.DateTime CREATEDATUTC { get; set; }
        public Nullable<System.DateTime> EXPIRESATUTC { get; set; }
    
        public virtual MATCH MATCH { get; set; }
        public virtual MODERATIONACTIONTYPE MODERATIONACTIONTYPE { get; set; }
        public virtual USER_PROFILE USER_PROFILE { get; set; }
        public virtual MODERATIONSCOPe MODERATIONSCOPe { get; set; }
        public virtual USER_PROFILE USER_PROFILE1 { get; set; }
    }
}
