//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryGuessWho.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOURNAMENT_4P
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOURNAMENT_4P()
        {
            this.TOURNAMENT_4P_MATCH = new HashSet<TOURNAMENT_4P_MATCH>();
            this.TOURNAMENT_4P_PLAYER = new HashSet<TOURNAMENT_4P_PLAYER>();
        }
    
        public int TOURNAMENTID { get; set; }
        public long HOSTUSERID { get; set; }
        public Nullable<long> CHARACTERSETID { get; set; }
        public int TURNSECONDS { get; set; }
        public byte STATUSID { get; set; }
        public System.DateTime CREATEDATUTC { get; set; }
    
        public virtual CHARACTER_SET CHARACTER_SET { get; set; }
        public virtual USER_PROFILE USER_PROFILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOURNAMENT_4P_MATCH> TOURNAMENT_4P_MATCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOURNAMENT_4P_PLAYER> TOURNAMENT_4P_PLAYER { get; set; }
    }
}
