//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryGuessWho.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOURNAMENT_4P_PLAYER
    {
        public int TOURNAMENTID { get; set; }
        public long USERID { get; set; }
        public byte SLOTNUMBER { get; set; }
    
        public virtual USER_PROFILE USER_PROFILE { get; set; }
        public virtual TOURNAMENT_4P TOURNAMENT_4P { get; set; }
    }
}
