namespace GuessWhoCore.Contracts.Faults
{
    public static class EmailVerificationFaultKeys
    {
        public const string CODE_REQUEST_NULL = "EMAILVERIFICATION_REQUEST_NULL";
        public const string CODE_UNEXPECTED_ERROR = "EMAILVERIFICATION_UNEXPECTED_ERROR";
        public const string CODE_ACCOUNT_NOT_FOUND = "EMAILVERIFICATION_ACCOUNT_NOT_FOUND";

        public const string CODE_CODE_INVALID_FORMAT = "EMAILVERIFICATION_CODE_INVALID_FORMAT";

        public const string CODE_CODE_INCORRECT = "EMAILVERIFICATION_CODE_INCORRECT";
        public const string CODE_CODE_EXPIRED = "EMAILVERIFICATION_CODE_EXPIRED";
        public const string CODE_CODE_ALREADY_USED = "EMAILVERIFICATION_CODE_ALREADY_USED";
        public const string CODE_CODE_MISSING = "EMAILVERIFICATION_CODE_MISSING";

        public const string CODE_RESEND_TOO_FREQUENT = "EMAILVERIFICATION_RESEND_TOO_FREQUENT";
        public const string CODE_RESEND_HOURLY_LIMIT_EXCEEDED = "EMAILVERIFICATION_RESEND_HOURLY_LIMIT_EXCEEDED";

        public const string CODE_EMAIL_VERIFICATION_FAILED = "EMAILVERIFICATION_VERIFICATION_FAILED";
        public const string CODE_TOKEN_CREATION_FAILED = "EMAILVERIFICATION_TOKEN_CREATION_FAILED";

        public const string CODE_EMAIL_RECIPIENT_INVALID = "EMAILVERIFICATION_RECIPIENT_INVALID";

        public const string CODE_SMTP_CONFIGURATION_MISSING = "EMAILVERIFICATION_SMTP_CONFIGURATION_MISSING";
        public const string CODE_SMTP_AUTHENTICATION_FAILED = "EMAILVERIFICATION_SMTP_AUTHENTICATION_FAILED";
        public const string CODE_SMTP_CONFIGURATION_ERROR = "EMAILVERIFICATION_SMTP_CONFIGURATION_ERROR";
        public const string CODE_SMTP_UNAVAILABLE = "EMAILVERIFICATION_SMTP_UNAVAILABLE";
        public const string CODE_EMAIL_SEND_FAILED = "EMAILVERIFICATION_EMAIL_SEND_FAILED";

        public const string CODE_CRYPTO_RANDOM_GENERATOR_UNAVAILABLE = "EMAILVERIFICATION_CRYPTO_RANDOM_UNAVAILABLE";
        public const string CODE_VERIFICATION_CODE_GENERATION_FAILED = "EMAILVERIFICATION_CODE_GENERATION_FAILED";
    }
}
