namespace GuessWhoCore.Contracts.Faults
{
    public static class PasswordRecoveryFaultKeys
    {
        public const string CODE_REQUEST_NULL = "PASSWORDRECOVERY_REQUEST_NULL";
        public const string CODE_UNEXPECTED_ERROR = "PASSWORDRECOVERY_UNEXPECTED_ERROR";
        public const string CODE_ACCOUNT_NOT_FOUND = "PASSWORDRECOVERY_ACCOUNT_NOT_FOUND";
        public const string CODE_RESEND_TOO_FREQUENT = "PASSWORDRECOVERY_RESEND_TOO_FREQUENT";
        public const string CODE_RESEND_HOURLY_LIMIT_EXCEEDED = "PASSWORDRECOVERY_RESEND_HOURLY_LIMIT_EXCEEDED";
        public const string CODE_UPDATE_PASSWORD_DB_FAILED = "PASSWORDRECOVERY_UPDATE_PASSWORD_DB_FAILED";
        public const string CODE_TOKEN_CREATION_FAILED = "PASSWORDRECOVERY_TOKEN_CREATION_FAILED";
        public const string CODE_EMAIL_MESSAGE_BUILD_FAILED = "PASSWORDRECOVERY_EMAIL_MESSAGE_BUILD_FAILED";
        public const string CODE_EMAIL_SENDER_RETURNED_NULL = "PASSWORDRECOVERY_EMAIL_SENDER_RETURNED_NULL";
        public const string CODE_CODE_EXPIRED = "PASSWORDRECOVERY_CODE_EXPIRED";
        public const string CODE_CODE_INVALID = "PASSWORDRECOVERY_CODE_INVALID";
    }
}
