namespace GuessWhoCore.Contracts.Faults
{
    public static class SecurityFaultsCodes
    {
        public const string REQUEST_NULL = "SECURITY_REQUEST_NULL";
        public const string ACCOUNT_NOT_FOUND = "SECURITY_ACCOUNT_NOT_FOUND";
        public const string UNEXPECTED_ERROR = "SECURITY_UNEXPECTED_ERROR";

        public const string CODE_INVALID_OR_EXPIRED = "SECURITY_CODE_INVALID_OR_EXPIRED";
        public const string CODE_RESEND_TOO_FREQUENT = "SECURITY_CODE_RESEND_TOO_FREQUENT";
        public const string CODE_RESEND_HOURLY_LIMIT_EXCEEDED = "SECURITY_CODE_RESEND_HOURLY_LIMIT_EXCEEDED";

        public const string CODE_INVALID_FORMAT = "SECURITY_CODE_INVALID_FORMAT";
        public const string CODE_ALREADY_USED = "SECURITY_CODE_ALREADY_USED";

        public const string EMAIL_VERIFICATION_TOKEN_CREATION_FAILED =
            "SECURITY_EMAIL_VERIFICATION_TOKEN_CREATION_FAILED";

        public const string RECOVERY_TOKEN_CREATION_FAILED =
            "SECURITY_RECOVERY_TOKEN_CREATION_FAILED";

        public const string EMAIL_SEND_FAILED = "SECURITY_EMAIL_SEND_FAILED";

        public const string SMTP_CONFIGURATION_MISSING =
            "SECURITY_SMTP_CONFIGURATION_MISSING";

        public const string SMTP_AUTHENTICATION_FAILED =
            "SECURITY_SMTP_AUTHENTICATION_FAILED";

        public const string SMTP_CONFIGURATION_ERROR =
            "SECURITY_SMTP_CONFIGURATION_ERROR";

        public const string SMTP_UNAVAILABLE =
            "SECURITY_SMTP_UNAVAILABLE";

        public const string CRYPTO_RANDOM_GENERATOR_UNAVAILABLE =
            "SECURITY_CRYPTO_RANDOM_GENERATOR_UNAVAILABLE";

        public const string VERIFICATION_CODE_GENERATION_FAILED =
            "SECURITY_VERIFICATION_CODE_GENERATION_FAILED";

        public const string EMAIL_VERIFICATION_FAILED =
            "SECURITY_EMAIL_VERIFICATION_FAILED";

        public const string EMAIL_RECIPIENT_INVALID =
            "SECURITY_EMAIL_RECIPIENT_INVALID";

        public const string EMAIL_VERIFICATION_CODE_INVALID_FORMAT =
            "SECURITY_EMAIL_VERIFICATION_CODE_INVALID_FORMAT";
    }
}
