namespace GuessWhoCore.Contracts.Faults
{
    public static class UserRegistrationFaultKeys
    {
        public const string CODE_REQUEST_NULL = "USERREGISTRATION_REQUEST_NULL";
        public const string CODE_UNEXPECTED_ERROR = "USERREGISTRATION_UNEXPECTED_ERROR";
        public const string CODE_ARGS_REQUIRED = "USERREGISTRATION_ARGS_REQUIRED";
        public const string CODE_EMAIL_REQUIRED = "USERREGISTRATION_EMAIL_REQUIRED";
        public const string CODE_EMAIL_ALREADY_EXISTS = "USERREGISTRATION_EMAIL_ALREADY_EXISTS";
        public const string CODE_PASSWORD_REQUIRED = "USERREGISTRATION_PASSWORD_REQUIRED";
        public const string CODE_DISPLAYNAME_REQUIRED = "USERREGISTRATION_DISPLAYNAME_REQUIRED";
        public const string CODE_TOKEN_CREATION_FAILED = "USERREGISTRATION_TOKEN_CREATION_FAILED";
        public const string CODE_NOWUTC_REQUIRED = "USERREGISTRATION_NOWUTC_REQUIRED";
        public const string CODE_VALIDATION_FAILED = "USERREGISTRATION_VALIDATION_FAILED";
        public const string CODE_EMAIL_INVALID = "USERREGISTRATION_EMAIL_INVALID";
        public const string CODE_DISPLAYNAME_INVALID = "USERREGISTRATION_DISPLAYNAME_INVALID";
        public const string CODE_PASSWORD_INVALID = "USERREGISTRATION_PASSWORD_INVALID";
    }
}
